user_string = input('введите что нибудь несколько знаков это будет строка: ')
print(user_string)
# print(type(user_string))
user_number_int = int(input('введите целое число: '))
print(user_number_int)
# print(type(user_number_int))
user_number_float = float(input('введите какое то число: '))
print(user_number_float)
# print(type(user_number_float))
